# Generated by Django 3.1.4 on 2020-12-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("tag", models.CharField(max_length=50)),
                ("rating", models.IntegerField()),
                ("wins", models.IntegerField()),
                ("losses", models.IntegerField()),
                ("last_match", models.DateField()),
                (
                    "logo",
                    models.ImageField(blank=True, upload_to="media/%Y/%m/%d"),
                ),
            ],
        ),
    ]
