# Generated by Django 3.1.4 on 2021-01-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('tag', models.TextField()),
                ('rating', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('last_match_time', models.DateField(default=None)),
                ('logo', models.URLField()),
                ('opendota_team_id', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
