# Generated by Django 3.1.4 on 2020-12-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_site", "0002_auto_20201224_1802"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="image",
            field=models.ManyToManyField(
                related_name="team", to="user_site.Image"
            ),
        ),
    ]
