# Generated by Django 3.1.4 on 2020-12-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0005_auto_20201224_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
