# Generated by Django 3.1.4 on 2020-12-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_site", "0006_auto_20201224_2036"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="image",
            new_name="logo",
        ),
    ]
