# Generated by Django 3.1.4 on 2020-12-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0009_auto_20201225_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.URLField(),
        ),
    ]
