# Generated by Django 3.1.4 on 2021-01-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_site", "0012_team_last_match_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="opendota_team_id",
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="team",
            name="tag",
            field=models.TextField(),
        ),
    ]
