# Generated by Django 3.1.4 on 2021-01-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_site", "0013_auto_20210104_2034"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="opendota_team_id",
            field=models.IntegerField(default=0),
        ),
    ]
